import React, { createContext, useContext, useState, useEffect } from 'react';

const T = {
  en: {
    unitId: "Unique Unit ID",
    newHere: "New to MediLocker?",
    signUp: "Create your account →",
    signupLabel: "REGISTRATION",
    signupTitle: "Create your MediLocker.",
    signupText: "Enter your details once. A unique Unit ID will be generated for future sign-ins.",
    fullName: "Full name",
    phone: "Phone number",
    accountType: "Account type",
    dob: "Date of birth",
    gender: "Gender",
    address: "Address",
    city: "City",
    state: "State",
    pin: "PIN code",
    govid: "Government ID / Aadhaar",
    insurance: "Medical insurance",
    allergy: "Allergies, if any",
    extra: "Additional details",
    consent: "I confirm that the information provided is accurate and I understand that a unique Unit ID will be generated.",
    createAccount: "Create account & generate Unit ID ↗",
    ready: "Your account is ready.",
    saveUnit: "Save this Unit ID. You will need it with your registered email to sign in.",
    continueLogin: "Continue to login →",
    navFeatures: "Features",
    navHowItWorks: "How It Works",
    navSecurity: "Clinical Safety",
    navPortals: "Access Portals",
    setLocation: "Set location",
    signIn: "Sign in ↗",
    signOut: "Sign out",
    eyebrow: "A calmer way to manage healthcare",
    hero1: "Your health story,",
    hero2: "in one place.",
    heroText: "MediLocker brings patient records, prescriptions, reports and medication routines into one beautifully organized digital experience.",
    enter: "Enter MediLocker ↗",
    seeHow: "See how it works ↓",
    sosHero: "Emergency SOS 102",
    designed: "Designed around the patient",
    records: "Records stay organized from first visit to follow-up.",
    overview: "HEALTH OVERVIEW",
    secured: "secured",
    goodMorning: "Good morning",
    profile: "PROFILE COMPLETENESS",
    keepUpdated: "Keep your medical story up to date.",
    medicalRecords: "Medical records",
    activeMeds: "Active medicines",
    nextMedication: "NEXT MEDICATION",
    afterLunch: "After lunch · 1:30 PM",
    feature1: "One medical home",
    feature1Text: "Prescriptions, reports and history in one organized space.",
    feature2: "Consent-led access",
    feature2Text: "Patients stay at the center of who can view their records.",
    feature3: "Medication to-do",
    feature3Text: "Turn prescription instructions into a simple daily routine.",
    access: "ACCESS PORTALS",
    choosePortal: "Choose your care portal.",
    portalText: "Every role gets a focused experience, while the patient's medical story remains at the center.",
    patient: "Patient",
    doctor: "Doctor",
    hospital: "Hospital",
    patientPortal: "Patient Portal",
    patientPortalDesc: "Manage records, daily to-dos, cabinet inventory, and OTP delegations.",
    doctorPortal: "Doctor Portal",
    doctorPortalDesc: "Search patients by Unit ID, review verified history, and conduct Vaidya OPD triage.",
    hospitalPortal: "Hospital Portal",
    hospitalPortalDesc: "Institutional patient records coordination, staff allocations, and audit oversight.",
    manageRecords: "Manage your records",
    accessCare: "Access patient care information",
    managePatients: "Manage authorized patient records",
    footer: "A digital home for organized healthcare.",
    welcome: "WELCOME TO MEDILOCKER",
    email: "Email address",
    password: "Password",
    continue: "Continue ↗",
    home: "Home",
    patientAccount: "Patient account",
    dashboard: "Dashboard",
    profilePage: "My profile",
    recordsPage: "Medical records",
    uploadPage: "Upload documents",
    todoPage: "Medication to-do",
    switchPortal: "Switch portal",
    patientDashboard: "PATIENT DASHBOARD",
    welcomeBack: "Welcome back",
    dashboardText: "Your health information is organized and ready when you need it.",
    viewTodo: "View medication to-do ↗",
    lockerId: "MEDILOCKER ID",
    lockerIdText: "Use this ID when sharing access with an authorized healthcare provider.",
    completeProfile: "Complete your profile to keep your health story up to date.",
    medsToday: "3 medicines are currently in your routine.",
    recordsStored: "Prescriptions, reports and documents stored.",
    quickAccess: "QUICK ACCESS",
    healthAtAGlance: "Your health at a glance.",
    profileDesc: "Personal and emergency details.",
    recordsDesc: "Prescriptions, reports and history.",
    uploadDesc: "Add prescriptions and reports.",
    todoDesc: "Follow today's medicine schedule.",
    profileHeading: "Your personal health profile.",
    profileHeadingText: "Keep essential information accurate for better continuity of care.",
    editProfile: "Edit details",
    verified: "Verified profile",
    dateBirth: "Date of birth",
    bloodGroup: "Blood group",
    location: "Location",
    emergency: "Emergency contact",
    emergencyText: "A trusted contact can be stored here for urgent situations.",
    recordsHeading: "Your medical story.",
    recordsHeadingText: "Prescriptions, reports and clinical history, organized by date.",
    uploadNew: "Upload new ↗",
    all: "All",
    prescriptions: "Prescriptions",
    reports: "Reports",
    prescription: "PRESCRIPTION",
    report: "LAB REPORT",
    view: "View",
    uploadHeading: "Add to your medical locker.",
    uploadHeadingText: "Upload prescriptions, reports or additional medical documents.",
    dropTitle: "Drop your document here",
    dropText: "or choose an image or PDF from your device",
    chooseFile: "Choose file",
    noFile: "No file selected",
    documentType: "Document type",
    other: "Other document",
    documentNote: "Note",
    saveDocument: "Save document ↗",
    todoHeading: "Today's medicine routine.",
    todoHeadingText: "Prescription instructions are organized into simple actions for your day.",
    today: "TODAY",
    completed: "tasks completed",
    routineProgress: "Daily routine progress",
    morning: "Morning",
    morningTime: "After breakfast · 8:00 AM",
    afternoon: "Afternoon",
    afternoonTime: "After lunch · 1:30 PM",
    night: "Night",
    nightTime: "After dinner · 9:00 PM",
    doseOne: "1 capsule · once in the morning",
    doseTwo: "1 tablet · once in the morning",
    doseThree: "1 capsule · second dose",
    doseFour: "1 tablet · if advised",
    doseFive: "1 capsule · third dose",
    doseSix: "1 tablet · once daily",
    withFood: "Take after food",
    asNeeded: "As directed by doctor",
    routine: "Follow prescribed routine",
    important: "Important",
    todoNotice: "This page converts prescription instructions into a visual checklist. Final medication instructions should always be followed according to the prescribing healthcare professional.",
    timelinePage: "Health timeline",
    inventoryPage: "Medicine cabinet",
    aiCompanionPage: "Medi-AI assistant",
    testsPage: "Lab tests & vitals",
    delegationPage: "Consent & access",
    trust1Title: "100% Patient Control",
    trust1Desc: "Instant 1-click access revocation",
    trust2Title: "ACID Database Engine",
    trust2Desc: "Enterprise PostgreSQL storage",
    trust3Title: "15-Min Dynamic OTP",
    trust3Desc: "6-digit code for clinical access",
    trust4Title: "Zero PHI Search Leak",
    trust4Desc: "Only Name & DOB on provider search"
  },
  bn: {
    unitId: "ইউনিক Unit ID",
    newHere: "MediLocker-এ নতুন?",
    signUp: "অ্যাকাউন্ট তৈরি করুন →",
    signupLabel: "রেজিস্ট্রেশন",
    signupTitle: "আপনার MediLocker তৈরি করুন।",
    signupText: "একবার তথ্য দিন। ভবিষ্যৎ সাইন-ইনের জন্য ইউনিক Unit ID তৈরি হবে।",
    fullName: "পুরো নাম",
    phone: "ফোন নম্বর",
    accountType: "অ্যাকাউন্টের ধরন",
    dob: "জন্মতারিখ",
    gender: "লিঙ্গ",
    address: "ঠিকানা",
    city: "শহর",
    state: "রাজ্য",
    pin: "পিন কোড",
    govid: "সরকারি ID / আধার",
    insurance: "মেডিকেল ইনস্যুরেন্স",
    allergy: "অ্যালার্জি, থাকলে",
    extra: "অতিরিক্ত তথ্য",
    consent: "আমি নিশ্চিত করছি যে তথ্য সঠিক এবং একটি ইউনিক Unit ID তৈরি হবে।",
    createAccount: "অ্যাকাউন্ট তৈরি ও Unit ID বানান ↗",
    ready: "আপনার অ্যাকাউন্ট প্রস্তুত।",
    saveUnit: "এই Unit ID সংরক্ষণ করুন। ইমেলের সঙ্গে সাইন ইন করতে এটি লাগবে।",
    continueLogin: "লগইনে যান →",
    navFeatures: "ফিচার",
    navHowItWorks: "কাজের ধারা",
    navSecurity: "ক্লিনিকাল নিরাপত্তা",
    navPortals: "পোর্টাল",
    setLocation: "অবস্থান সেট করুন",
    signIn: "সাইন ইন ↗",
    signOut: "সাইন আউট",
    eyebrow: "স্বাস্থ্য ব্যবস্থাপনার একটি সহজ উপায়",
    hero1: "আপনার স্বাস্থ্যকথা,",
    hero2: "এক জায়গায়।",
    heroText: "MediLocker রোগীর রেকর্ড, প্রেসক্রিপশন, রিপোর্ট এবং ওষুধের রুটিনকে একটি সুন্দরভাবে সাজানো ডিজিটাল অভিজ্ঞতায় নিয়ে আসে।",
    enter: "MediLocker-এ প্রবেশ করুন ↗",
    seeHow: "কীভাবে কাজ করে দেখুন ↓",
    sosHero: "জরুরি SOS ১০২",
    designed: "রোগীকে কেন্দ্র করে তৈরি",
    records: "প্রথম সাক্ষাৎ থেকে ফলো-আপ পর্যন্ত রেকর্ড সাজানো থাকে।",
    overview: "স্বাস্থ্য পর্যালোচনা",
    secured: "সুরক্ষিত",
    goodMorning: "সুপ্রভাত",
    profile: "প্রোফাইল সম্পূর্ণতা",
    keepUpdated: "আপনার চিকিৎসার তথ্য আপডেট রাখুন।",
    medicalRecords: "চিকিৎসা রেকর্ড",
    activeMeds: "চলমান ওষুধ",
    nextMedication: "পরবর্তী ওষুধ",
    afterLunch: "দুপুরের খাবারের পর · ১:৩০",
    feature1: "একটি মেডিকেল হোম",
    feature1Text: "প্রেসক্রিপশন, রিপোর্ট ও ইতিহাস এক জায়গায়।",
    feature2: "অনুমতিভিত্তিক অ্যাক্সেস",
    feature2Text: "কে রেকর্ড দেখতে পারবেন তা রোগী নিয়ন্ত্রণ করেন।",
    feature3: "ওষুধের টু-ডু",
    feature3Text: "প্রেসক্রিপশনের নির্দেশকে সহজ দৈনিক রুটিনে রূপান্তর করুন।",
    access: "অ্যাক্সেস পোর্টাল",
    choosePortal: "আপনার কেয়ার পোর্টাল বেছে নিন।",
    portalText: "প্রতিটি ভূমিকার জন্য আলাদা অভিজ্ঞতা, আর রোগীর চিকিৎসার গল্প থাকে কেন্দ্রে।",
    patient: "রোগী",
    doctor: "ডাক্তার",
    hospital: "হাসপাতাল",
    patientPortal: "রোগী পোর্টাল",
    patientPortalDesc: "রেকর্ড, দৈনন্দিন কাজ, ওষুধের ক্যাবিনেট এবং ওটিপি প্রতিনিধি পরিচালনা করুন।",
    doctorPortal: "ডাক্তার পোর্টাল",
    doctorPortalDesc: "ইউনিট আইডি দিয়ে রোগী খুঁজুন, রেকর্ড দেখুন এবং বৈদ্য ওপিডি ট্রায়াজ করুন।",
    hospitalPortal: "হাসপাতাল পোর্টাল",
    hospitalPortalDesc: "প্রতিষ্ঠানগত রেকর্ড সমন্বয়, স্টাফ পরিচালনা এবং অডিট নজরদারি।",
    manageRecords: "আপনার রেকর্ড পরিচালনা করুন",
    accessCare: "অনুমোদিত রোগীর তথ্য দেখুন",
    managePatients: "অনুমোদিত রোগীর রেকর্ড পরিচালনা করুন",
    footer: "সুশৃঙ্খল স্বাস্থ্যসেবার জন্য একটি ডিজিটাল ঠিকানা।",
    welcome: "MEDILOCKER-এ স্বাগতম",
    email: "ইমেইল ঠিকানা",
    password: "পাসওয়ার্ড",
    continue: "চালিয়ে যান ↗",
    home: "হোম",
    patientAccount: "রোগীর অ্যাকাউন্ট",
    dashboard: "ড্যাশবোর্ড",
    profilePage: "আমার প্রোফাইল",
    recordsPage: "চিকিৎসা রেকর্ড",
    uploadPage: "ডকুমেন্ট আপলোড",
    todoPage: "ওষুধের টু-ডু",
    switchPortal: "পোর্টাল বদলান",
    patientDashboard: "রোগী ড্যাশবোর্ড",
    welcomeBack: "আবার স্বাগতম",
    dashboardText: "আপনার স্বাস্থ্য তথ্য সাজানো এবং প্রয়োজনে প্রস্তুত।",
    viewTodo: "ওষুধের টু-ডু দেখুন ↗",
    lockerId: "মেডিলকার আইডি",
    lockerIdText: "অনুমোদিত স্বাস্থ্যসেবা প্রদানকারীর সঙ্গে অ্যাক্সেস শেয়ার করতে এই আইডি ব্যবহার করুন।",
    completeProfile: "আপনার স্বাস্থ্যকথা আপডেট রাখতে প্রোফাইল সম্পূর্ণ করুন।",
    medsToday: "আপনার রুটিনে বর্তমানে ৩টি ওষুধ আছে।",
    recordsStored: "প্রেসক্রিপশন, রিপোর্ট ও ডকুমেন্ট সংরক্ষিত।",
    quickAccess: "দ্রুত অ্যাক্সেস",
    healthAtAGlance: "এক নজরে আপনার স্বাস্থ্য।",
    profileDesc: "ব্যক্তিগত ও জরুরি তথ্য।",
    recordsDesc: "প্রেসক্রিপশন, রিপোর্ট ও ইতিহাস।",
    uploadDesc: "প্রেসক্রিপশন ও রিপোর্ট যোগ করুন।",
    todoDesc: "আজকের ওষুধের সময়সূচি অনুসরণ করুন।",
    profileHeading: "আপনার ব্যক্তিগত স্বাস্থ্য প্রোফাইল।",
    profileHeadingText: "চিকিৎসার ধারাবাহিকতার জন্য গুরুত্বপূর্ণ তথ্য সঠিক রাখুন।",
    editProfile: "তথ্য সম্পাদনা",
    verified: "যাচাইকৃত প্রোফাইল",
    dateBirth: "জন্মতারিখ",
    bloodGroup: "রক্তের গ্রুপ",
    location: "অবস্থান",
    emergency: "জরুরি যোগাযোগ",
    emergencyText: "জরুরি পরিস্থিতির জন্য এখানে একজন বিশ্বস্ত যোগাযোগ রাখা যেতে পারে।",
    recordsHeading: "আপনার চিকিৎসার গল্প।",
    recordsHeadingText: "প্রেসক্রিপশন, রিপোর্ট ও চিকিৎসার ইতিহাস তারিখ অনুযায়ী সাজানো।",
    uploadNew: "নতুন আপলোড ↗",
    all: "সব",
    prescriptions: "প্রেসক্রিপশন",
    reports: "রিপোর্ট",
    prescription: "প্রেসক্রিপশন",
    report: "ল্যাব রিপোর্ট",
    view: "দেখুন",
    uploadHeading: "আপনার মেডিকেল লকারে যোগ করুন।",
    uploadHeadingText: "প্রেসক্রিপশন, রিপোর্ট বা অন্যান্য চিকিৎসা ডকুমেন্ট আপলোড করুন।",
    dropTitle: "ডকুমেন্ট এখানে রাখুন",
    dropText: "অথবা ডিভাইস থেকে ছবি বা PDF বেছে নিন",
    chooseFile: "ফাইল বেছে নিন",
    noFile: "কোনো ফাইল বাছাই করা হয়নি",
    documentType: "ডকুমেন্টের ধরন",
    other: "অন্যান্য ডকুমেন্ট",
    documentNote: "নোট",
    saveDocument: "ডকুমেন্ট সংরক্ষণ করুন ↗",
    todoHeading: "আজকের ওষুধের রুটিন।",
    todoHeadingText: "প্রেসক্রিপশনের নির্দেশনাগুলো আপনার দিনের সহজ কাজ হিসেবে সাজানো হয়েছে।",
    today: "আজ",
    completed: "টি কাজ সম্পন্ন",
    routineProgress: "দৈনিক রুটিনের অগ্রগতি",
    morning: "সকাল",
    morningTime: "জলখাবারের পর · সকাল ৮:০০",
    afternoon: "দুপুর",
    afternoonTime: "দুপুরের খাবারের পর · ১:৩০",
    night: "রাত",
    nightTime: "রাতের খাবারের পর · ৯:০০",
    doseOne: "১ ক্যাপসুল · সকালে একবার",
    doseTwo: "১ ট্যাবলেট · সকালে একবার",
    doseThree: "১ ক্যাপসুল · দ্বিতীয় ডোজ",
    doseFour: "১ ট্যাবলেট · প্রয়োজনে",
    doseFive: "১ ক্যাপসুল · তৃতীয় ডোজ",
    doseSix: "১ ট্যাবলেট · দিনে একবার",
    withFood: "খাবারের পরে নিন",
    asNeeded: "ডাক্তারের নির্দেশ অনুযায়ী",
    routine: "নির্ধারিত রুটিন অনুসরণ করুন",
    important: "গুরুত্বপূর্ণ",
    todoNotice: "এই পেজটি প্রেসক্রিপশনের নির্দেশনাকে একটি ভিজ্যুয়াল চেকলিস্টে রূপান্তর করে। চূড়ান্ত ওষুধের নির্দেশনা অবশ্যই চিকিৎসকের পরামর্শ অনুযায়ী অনুসরণ করতে হবে।",
    timelinePage: "স্বাস্থ্য টাইমলাইন",
    inventoryPage: "ওষুধের কেবিনেট",
    aiCompanionPage: "মেডি-এআই সহকারী",
    testsPage: "ল্যাব টেস্ট ও ভাইটালস",
    delegationPage: "সম্মতি ও অ্যাক্সেস",
    trust1Title: "১০০% রোগীর নিয়ন্ত্রণ",
    trust1Desc: "১-ক্লিকে তাৎক্ষণিক অ্যাক্সেস প্রত্যাহার",
    trust2Title: "ACID ডাটাবেস ইঞ্জিন",
    trust2Desc: "এন্টারপ্রাইজ PostgreSQL স্টোরেজ",
    trust3Title: "১৫-মিনিট ডায়নামিক OTP",
    trust3Desc: "ক্লিনিকাল অ্যাক্সেসের জন্য ৬-সংখ্যার কোড",
    trust4Title: "জিরো PHI সার্চ লিক",
    trust4Desc: "সন্ধানে কেবল নাম ও জন্মতারিখ দৃশ্যমান"
  }
};

const base = T.en;

T.hi = {
  ...base,
  navFeatures: "फीचर्स",
  navHowItWorks: "कार्यप्रणाली",
  navSecurity: "चिकित्सीय सुरक्षा",
  navPortals: "पोर्टल",
  setLocation: "स्थान सेट करें",
  signIn: "साइन इन ↗",
  signOut: "साइन आउट",
  eyebrow: "स्वास्थ्य प्रबंधन का आसान तरीका",
  hero1: "आपकी स्वास्थ्य कहानी,",
  hero2: "एक ही जगह।",
  heroText: "MediLocker मरीज के रिकॉर्ड, प्रिस्क्रिप्शन, रिपोर्ट और दवाइयों की दिनचर्या को एक व्यवस्थित डिजिटल अनुभव में लाता है।",
  enter: "MediLocker में जाएँ ↗",
  seeHow: "देखें कैसे काम करता है ↓",
  sosHero: "आपातकालीन SOS 102",
  designed: "मरीज को केंद्र में रखकर बनाया गया",
  records: "पहली मुलाकात से फॉलो-अप तक रिकॉर्ड व्यवस्थित रहते हैं।",
  overview: "स्वास्थ्य अवलोकन",
  secured: "सुरक्षित",
  goodMorning: "सुप्रभात",
  profile: "प्रोफाइल पूर्णता",
  keepUpdated: "अपनी चिकित्सा जानकारी अपडेट रखें।",
  medicalRecords: "मेडिकल रिकॉर्ड",
  activeMeds: "सक्रिय दवाइयाँ",
  nextMedication: "अगली दवा",
  afterLunch: "दोपहर के भोजन के बाद · 1:30",
  feature1: "एक मेडिकल होम",
  feature1Text: "प्रिस्क्रिप्शन, रिपोर्ट और इतिहास एक व्यवस्थित जगह पर।",
  feature2: "सहमति आधारित एक्सेस",
  feature2Text: "मरीज तय करते हैं कि उनके रिकॉर्ड कौन देख सकता है।",
  feature3: "दवा टू-डू",
  feature3Text: "प्रिस्क्रिप्शन निर्देशों को आसान दैनिक दिनचर्या में बदलें।",
  access: "एक्सेस पोर्टल",
  choosePortal: "अपना केयर पोर्टल चुनें।",
  portalText: "हर भूमिका के लिए अलग अनुभव, जबकि मरीज की मेडिकल कहानी केंद्र में रहती है।",
  patient: "मरीज",
  doctor: "डॉक्टर",
  hospital: "अस्पताल",
  patientPortal: "मरीज पोर्टल",
  patientPortalDesc: "रिकॉर्ड, दैनिक कार्य, दवा कैबिनेट और ओटीपी सहमति प्रबंधित करें।",
  doctorPortal: "डॉक्टर पोर्टल",
  doctorPortalDesc: "यूनिट आईडी से मरीज खोजें, रिकॉर्ड देखें और वैद्य ओपीडी सेवा दें।",
  hospitalPortal: "अस्पताल पोर्टल",
  hospitalPortalDesc: "संस्थागत रिकॉर्ड समन्वय, कर्मचारी आवंटन और ऑडिट निगरानी।",
  manageRecords: "अपने रिकॉर्ड प्रबंधित करें",
  accessCare: "अनुमत मरीज की जानकारी देखें",
  managePatients: "अनुमत मरीज के रिकॉर्ड प्रबंधित करें",
  welcome: "MEDILOCKER में आपका स्वागत है",
  home: "होम",
  patientAccount: "मरीज खाता",
  dashboard: "डैशबोर्ड",
  profilePage: "मेरी प्रोफाइल",
  recordsPage: "मेडिकल रिकॉर्ड",
  uploadPage: "डॉक्यूमेंट अपलोड",
  todoPage: "दवा टू-डू",
  switchPortal: "पोर्टल बदलें",
  patientDashboard: "मरीज डैशबोर्ड",
  welcomeBack: "वापसी पर स्वागत है",
  dashboardText: "आपकी स्वास्थ्य जानकारी व्यवस्थित है और जरूरत पड़ने पर तैयार है।",
  viewTodo: "दवा टू-डू देखें ↗",
  lockerId: "मेडिलॉकर आईडी",
  lockerIdText: "अनुमत स्वास्थ्य सेवा प्रदाता के साथ एक्सेस साझा करने के लिए इस आईडी का उपयोग करें।",
  quickAccess: "त्वरित एक्सेस",
  healthAtAGlance: "एक नज़र में आपका स्वास्थ्य।",
  profileHeading: "आपकी व्यक्तिगत स्वास्थ्य प्रोफाइल।",
  profileHeadingText: "बेहतर उपचार निरंतरता के लिए जरूरी जानकारी सही रखें।",
  editProfile: "विवरण संपादित करें",
  verified: "सत्यापित प्रोफाइल",
  fullName: "पूरा नाम",
  dateBirth: "जन्म तिथि",
  bloodGroup: "ब्लड ग्रुप",
  phone: "फोन नंबर",
  location: "स्थान",
  emergency: "आपातकालीन संपर्क",
  emergencyText: "आपात स्थिति के लिए यहां विश्वसनीय संपर्क रखा जा सकता है।",
  recordsHeading: "आपकी मेडिकल कहानी।",
  recordsHeadingText: "प्रिस्क्रिप्शन, रिपोर्ट और चिकित्सा इतिहास तारीख के अनुसार व्यवस्थित।",
  uploadNew: "नया अपलोड ↗",
  all: "सभी",
  prescriptions: "प्रिस्क्रिप्शन",
  reports: "रिपोर्ट",
  prescription: "प्रिस्क्रिप्शन",
  report: "लैब रिपोर्ट",
  view: "देखें",
  uploadHeading: "अपने मेडिकल लॉकर में जोड़ें।",
  uploadHeadingText: "प्रिस्क्रिप्शन, रिपोर्ट या अन्य मेडिकल डॉक्यूमेंट अपलोड करें।",
  dropTitle: "डॉक्यूमेंट यहां रखें",
  dropText: "या अपने डिवाइस से तस्वीर या PDF चुनें",
  chooseFile: "फाइल चुनें",
  noFile: "कोई फाइल नहीं चुनी गई",
  documentType: "डॉक्यूमेंट प्रकार",
  other: "अन्य डॉक्यूमेंट",
  documentNote: "नोट",
  saveDocument: "डॉक्यूमेंट सेव करें ↗",
  todoHeading: "आज की दवा की दिनचर्या।",
  todoHeadingText: "प्रिस्क्रिप्शन निर्देशों को आपके दिन के आसान कार्यों में व्यवस्थित किया गया है।",
  today: "आज",
  completed: "कार्य पूरे",
  routineProgress: "दैनिक रूटीन की प्रगति",
  morning: "सुबह",
  morningTime: "नाश्ते के बाद · 8:00 AM",
  afternoon: "दोपहर",
  afternoonTime: "दोपहर के भोजन के बाद · 1:30 PM",
  night: "रात",
  nightTime: "रात के खाने के बाद · 9:00 PM",
  withFood: "खाने के बाद लें",
  asNeeded: "डॉक्टर के निर्देशानुसार",
  routine: "निर्धारित रूटीन का पालन करें",
  important: "महत्वपूर्ण",
  trust1Title: "100% मरीज का नियंत्रण",
  trust1Desc: "तुरंत 1-क्लिक एक्सेस रद्दीकरण",
  trust2Title: "ACID डेटाबेस इंजन",
  trust2Desc: "एंटरप्राइज PostgreSQL स्टोरेज",
  trust3Title: "15-मिनट डायनामिक OTP",
  trust3Desc: "चिकित्सीय एक्सेस हेतु 6-अंकीय कोड",
  trust4Title: "शून्य डेटा लीक सर्च",
  trust4Desc: "सर्च पर केवल नाम व जन्मतिथि दृश्यमान"
};

T.mr = {
  ...base,
  navFeatures: "वैशिष्ट्ये",
  navHowItWorks: "कसे कार्य करते",
  navSecurity: "वैद्यकीय सुरक्षा",
  navPortals: "पोर्टल",
  setLocation: "स्थान सेट करा",
  signIn: "साइन इन ↗",
  signOut: "साइन आउट",
  eyebrow: "आरोग्य व्यवस्थापनाचा सोपा मार्ग",
  hero1: "तुमची आरोग्यकथा,",
  hero2: "एका ठिकाणी.",
  heroText: "MediLocker रुग्णांचे रेकॉर्ड, प्रिस्क्रिप्शन, रिपोर्ट आणि औषधांची दिनचर्या एका व्यवस्थित डिजिटल अनुभवात आणते.",
  enter: "MediLocker मध्ये प्रवेश करा ↗",
  seeHow: "कसे काम करते ते पहा ↓",
  sosHero: "आपत्कालीन SOS 102",
  designed: "रुग्णाला केंद्रस्थानी ठेवून तयार",
  overview: "आरोग्य आढावा",
  goodMorning: "सुप्रभात",
  profile: "प्रोफाइल पूर्णता",
  medicalRecords: "वैद्यकीय रेकॉर्ड",
  activeMeds: "सक्रिय औषधे",
  nextMedication: "पुढील औषध",
  afterLunch: "दुपारच्या जेवणानंतर · 1:30",
  feature1: "एक मेडिकल होम",
  feature2: "संमतीवर आधारित प्रवेश",
  feature3: "औषध टू-डू",
  access: "प्रवेश पोर्टल",
  choosePortal: "तुमचा केअर पोर्टल निवडा.",
  portalText: "प्रत्येक भूमिकेसाठी वेगळा अनुभव, आणि रुग्णाची वैद्यकीय कथा केंद्रस्थानी.",
  patient: "रुग्ण",
  doctor: "डॉक्टर",
  hospital: "रुग्णालय",
  patientPortal: "रुग्ण पोर्टल",
  patientPortalDesc: "रेकॉर्ड, दैनंदिन कामे, औषध कॅबिनेट आणि ओटीपी संमती व्यवस्थापित करा.",
  doctorPortal: "डॉक्टर पोर्टल",
  doctorPortalDesc: "युनिट आयडीने रुग्ण शोधा, इतिहास तपासा आणि वैद्य ओपीडी ट्रायज करा.",
  hospitalPortal: "रुग्णालय पोर्टल",
  hospitalPortalDesc: "संस्थात्मक रेकॉर्ड समन्वय, कर्मचारी वाटप आणि ऑडिट निरीक्षण.",
  manageRecords: "तुमचे रेकॉर्ड व्यवस्थापित करा",
  accessCare: "परवानगी असलेली रुग्ण माहिती पहा",
  managePatients: "परवानगी असलेले रेकॉर्ड व्यवस्थापित करा",
  welcome: "MEDILOCKER मध्ये स्वागत आहे",
  home: "होम",
  patientAccount: "रुग्ण खाते",
  dashboard: "डॅशबोर्ड",
  profilePage: "माझे प्रोफाइल",
  recordsPage: "वैद्यकीय रेकॉर्ड",
  uploadPage: "डॉक्युमेंट अपलोड",
  todoPage: "औषध टू-डू",
  switchPortal: "पोर्टल बदला",
  patientDashboard: "रुग्ण डॅशबोर्ड",
  welcomeBack: "पुन्हा स्वागत आहे",
  dashboardText: "तुमची आरोग्य माहिती व्यवस्थित आणि गरजेच्या वेळी तयार आहे.",
  viewTodo: "औषध टू-डू पहा ↗",
  quickAccess: "जलद प्रवेश",
  healthAtAGlance: "एका नजरेत तुमचे आरोग्य.",
  profileHeading: "तुमचे वैयक्तिक आरोग्य प्रोफाइल.",
  profileHeadingText: "उपचाराच्या सातत्यासाठी महत्त्वाची माहिती अचूक ठेवा.",
  editProfile: "तपशील संपादित करा",
  verified: "सत्यापित प्रोफाइल",
  fullName: "पूर्ण नाव",
  dateBirth: "जन्मतारीख",
  bloodGroup: "रक्तगट",
  phone: "फोन नंबर",
  location: "स्थान",
  emergency: "आपत्कालीन संपर्क",
  emergencyText: "तातडीच्या परिस्थितीसाठी येथे विश्वासू संपर्क ठेवता येईल.",
  recordsHeading: "तुमची वैद्यकीय कथा.",
  recordsHeadingText: "प्रिस्क्रिप्शन, रिपोर्ट आणि वैद्यकीय इतिहास तारखेनुसार व्यवस्थित.",
  uploadNew: "नवीन अपलोड ↗",
  all: "सर्व",
  prescriptions: "प्रिस्क्रिप्शन",
  reports: "रिपोर्ट",
  prescription: "प्रिस्क्रिप्शन",
  report: "लॅब रिपोर्ट",
  view: "पहा",
  uploadHeading: "तुमच्या मेडिकल लॉकरमध्ये जोडा.",
  uploadHeadingText: "प्रिस्क्रिप्शन, रिपोर्ट किंवा इतर वैद्यकीय कागदपत्रे अपलोड करा.",
  dropTitle: "डॉक्युमेंट येथे टाका",
  dropText: "किंवा डिव्हाइसवरून फोटो किंवा PDF निवडा",
  chooseFile: "फाइल निवडा",
  noFile: "फाइल निवडलेली नाही",
  documentType: "डॉक्युमेंट प्रकार",
  other: "इतर डॉक्युमेंट",
  documentNote: "नोट",
  saveDocument: "डॉक्युमेंट जतन करा ↗",
  todoHeading: "आजची औषधांची दिनचर्या.",
  todoHeadingText: "प्रिस्क्रिप्शनच्या सूचना तुमच्या दिवसातील सोप्या कृतींमध्ये मांडल्या आहेत.",
  today: "आज",
  completed: "कामे पूर्ण",
  routineProgress: "दैनंदिन रुटीन प्रगती",
  morning: "सकाळ",
  afternoon: "दुपार",
  night: "रात्र",
  withFood: "जेवणानंतर घ्या",
  asNeeded: "डॉक्टरांच्या सूचनेनुसार",
  routine: "ठरवलेल्या रुटीनचे पालन करा",
  important: "महत्त्वाचे",
  trust1Title: "१००% रुग्णांचे नियंत्रण",
  trust1Desc: "१-क्लिकमध्ये तत्काळ प्रवेश रद्द",
  trust2Title: "ACID डेटाबेस इंजिन",
  trust2Desc: "एंटरप्राइज PostgreSQL स्टोरेज",
  trust3Title: "१५-मिनिट डायनॅमिक OTP",
  trust3Desc: "क्लिनिकल प्रवेशासाठी ६-अंकी कोड",
  trust4Title: "झिरो PHI सर्च लीक",
  trust4Desc: "शोधताना केवळ नाव व जन्मतारीख दृश्यमान"
};

T.ur = {
  ...base,
  navFeatures: "خصوصیات",
  navHowItWorks: "طریقہ کار",
  navSecurity: "طبی حفاظت",
  navPortals: "پورٹلز",
  setLocation: "مقام سیٹ کریں",
  signIn: "سائن اِن ↗",
  signOut: "سائن آؤٹ",
  eyebrow: "صحت سنبھالنے کا آسان طریقہ",
  hero1: "آپ کی صحت کی کہانی،",
  hero2: "ایک ہی جگہ۔",
  heroText: "MediLocker مریض کے ریکارڈ، نسخے، رپورٹس اور ادویات کی روٹین کو ایک منظم ڈیجیٹل تجربے میں لاتا ہے۔",
  enter: "MediLocker میں داخل ہوں ↗",
  seeHow: "دیکھیں کیسے کام کرتا ہے ↓",
  sosHero: "ہنگامی SOS 102",
  designed: "مریض کو مرکز میں رکھ کر بنایا گیا",
  overview: "صحت کا جائزہ",
  goodMorning: "صبح بخیر",
  profile: "پروفائل کی تکمیل",
  medicalRecords: "طبی ریکارڈ",
  activeMeds: "فعال ادویات",
  nextMedication: "اگلی دوا",
  afterLunch: "دوپہر کے کھانے کے بعد · 1:30",
  feature1: "ایک میڈیکل ہوم",
  feature2: "رضامندی پر مبنی رسائی",
  feature3: "ادویات کی ٹو ڈو",
  access: "رسائی پورٹلز",
  choosePortal: "اپنا کیئر پورٹل منتخب کریں۔",
  portalText: "ہر کردار کے لیے الگ تجربہ، جبکہ مریض کی طبی کہانی مرکز میں رہتی ہے۔",
  patient: "مریض",
  doctor: "ڈاکٹر",
  hospital: "ہسپتال",
  patientPortal: "مریض پورٹل",
  patientPortalDesc: "ریکارڈز، روزمرہ کام، ادویات کیبنٹ اور او ٹی پی وفود کا انتظام کریں۔",
  doctorPortal: "ڈاکٹر پورٹل",
  doctorPortalDesc: "یونٹ آئی ڈی سے مریض تلاش کریں اور ویدیہ او پی ڈی ٹریاج انجام دیں۔",
  hospitalPortal: "ہسپتال پورٹل",
  hospitalPortalDesc: "ادارہ جاتی ریکارڈز کوآرڈینیشن، عملہ کا انتظام اور آڈٹ نگرانی۔",
  manageRecords: "اپنے ریکارڈ سنبھالیں",
  accessCare: "مجاز مریض کی معلومات دیکھیں",
  managePatients: "مجاز مریض کے ریکارڈ سنبھالیں",
  welcome: "MEDILOCKER میں خوش آمدید",
  home: "ہوم",
  patientAccount: "مریض اکاؤنٹ",
  dashboard: "ڈیش بورڈ",
  profilePage: "میرا پروفائل",
  recordsPage: "طبی ریکارڈ",
  uploadPage: "دستاویز اپ لوڈ",
  todoPage: "ادویات کی ٹو ڈو",
  switchPortal: "پورٹل تبدیل کریں",
  patientDashboard: "مریض ڈیش بورڈ",
  welcomeBack: "خوش آمدید",
  dashboardText: "آپ کی صحت کی معلومات منظم ہے اور ضرورت کے وقت تیار ہے۔",
  viewTodo: "ادویات کی ٹو ڈو دیکھیں ↗",
  quickAccess: "فوری رسائی",
  healthAtAGlance: "ایک نظر میں آپ کی صحت۔",
  profileHeading: "آپ کا ذاتی صحت پروفائل۔",
  profileHeadingText: "بہتر نگہداشت کے تسلسل کے لیے ضروری معلومات درست رکھیں۔",
  editProfile: "تفصیلات میں ترمیم",
  verified: "تصدیق شدہ پروفائل",
  fullName: "پورا نام",
  dateBirth: "تاریخ پیدائش",
  bloodGroup: "بلڈ گروپ",
  phone: "فون نمبر",
  location: "مقام",
  emergency: "ہنگامی رابطہ",
  emergencyText: "ہنگامی صورت حال کے لیے یہاں قابل اعتماد رابطہ رکھا جا سکتا ہے۔",
  recordsHeading: "آپ کی طبی کہانی۔",
  recordsHeadingText: "نسخے، رپورٹس اور طبی تاریخ تاریخ کے مطابق منظم۔",
  uploadNew: "نیا اپ لوڈ ↗",
  all: "سب",
  prescriptions: "نسخے",
  reports: "رپورٹس",
  prescription: "نسخہ",
  report: "لیب رپورٹ",
  view: "دیکھیں",
  uploadHeading: "اپنے میڈیکل لاکر میں شامل کریں۔",
  uploadHeadingText: "نسخے، رپورٹس یا دیگر طبی دستاویزات اپ لوڈ کریں۔",
  dropTitle: "دستاویز یہاں رکھیں",
  dropText: "یا اپنے آلے سے تصویر یا PDF منتخب کریں",
  chooseFile: "فائل منتخب کریں",
  noFile: "کوئی فائل منتخب نہیں",
  documentType: "دستاویز کی قسم",
  other: "دیگر دستاویز",
  documentNote: "نوٹ",
  saveDocument: "دستاویز محفوظ کریں ↗",
  todoHeading: "آج کی دوا کی روٹین۔",
  todoHeadingText: "نسخے کی ہدایات کو آپ کے دن کے آسان کاموں میں منظم کیا گیا ہے۔",
  today: "آج",
  completed: "کام مکمل",
  routineProgress: "روزانہ روٹین کی پیش رفت",
  morning: "صبح",
  afternoon: "دوپہر",
  night: "رات",
  withFood: "کھانے کے بعد لیں",
  asNeeded: "ڈاکٹر کی ہدایت کے مطابق",
  routine: "مقررہ روٹین پر عمل کریں",
  important: "اہم",
  trust1Title: "۱۰۰٪ مریض کا کنٹرول",
  trust1Desc: "فوری ایک کلک رسائی منسوخی",
  trust2Title: "ACID ڈیٹا بیس انجن",
  trust2Desc: "انٹرپرائز PostgreSQL اسٹوریج",
  trust3Title: "۱۵ منٹ متحرک OTP",
  trust3Desc: "طبی رسائی کے لیے ۶ ہندسوں کا کوڈ",
  trust4Title: "صفر ذاتی ڈیٹا لیک",
  trust4Desc: "تلاش پر صرف نام اور تاریخ پیدائش ظاہر"
};

T.pa = {
  ...base,
  navFeatures: "ਫੀਚਰ",
  navHowItWorks: "ਕੰਮ ਕਿਵੇਂ ਕਰਦਾ ਹੈ",
  navSecurity: "ਕਲੀਨਿਕਲ ਸੁਰੱਖਿਆ",
  navPortals: "ਪੋਰਟਲ",
  setLocation: "ਟਿਕਾਣਾ ਸੈੱਟ ਕਰੋ",
  signIn: "ਸਾਈਨ ਇਨ ↗",
  signOut: "ਸਾਈਨ ਆਊਟ",
  eyebrow: "ਸਿਹਤ ਸੰਭਾਲ ਦਾ ਆਸਾਨ ਤਰੀਕਾ",
  hero1: "ਤੁਹਾਡੀ ਸਿਹਤ ਦੀ ਕਹਾਣੀ,",
  hero2: "ਇੱਕ ਹੀ ਥਾਂ।",
  heroText: "MediLocker ਮਰੀਜ਼ ਦੇ ਰਿਕਾਰਡ, ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ, ਰਿਪੋਰਟਾਂ ਅਤੇ ਦਵਾਈਆਂ ਦੀ ਰੁਟੀਨ ਨੂੰ ਇੱਕ ਡਿਜ਼ੀਟਲ ਅਨੁਭਵ ਵਿੱਚ ਲਿਆਉਂਦਾ ਹੈ।",
  enter: "MediLocker ਵਿੱਚ ਜਾਓ ↗",
  seeHow: "ਵੇਖੋ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ ↓",
  sosHero: "ਐਮਰਜੈਂਸੀ SOS 102",
  designed: "ਮਰੀਜ਼ ਨੂੰ ਕੇਂਦਰ ਵਿੱਚ ਰੱਖ ਕੇ ਬਣਾਇਆ",
  overview: "ਸਿਹਤ ਝਲਕ",
  goodMorning: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
  profile: "ਪ੍ਰੋਫਾਈਲ ਪੂਰਨਤਾ",
  medicalRecords: "ਮੈਡੀਕਲ ਰਿਕਾਰਡ",
  activeMeds: "ਚੱਲ ਰਹੀਆਂ ਦਵਾਈਆਂ",
  nextMedication: "ਅਗਲੀ ਦਵਾਈ",
  afterLunch: "ਦੁਪਹਿਰ ਦੇ ਖਾਣੇ ਤੋਂ ਬਾਅਦ · 1:30",
  feature1: "ਇੱਕ ਮੈਡੀਕਲ ਹੋਮ",
  feature2: "ਸਹਿਮਤੀ-ਅਧਾਰਿਤ ਐਕਸੈੱਸ",
  feature3: "ਦਵਾਈ ਟੂ-ਡੂ",
  access: "ਐਕਸੈੱਸ ਪੋਰਟਲ",
  choosePortal: "ਆਪਣਾ ਕੇਅਰ ਪੋਰਟਲ ਚੁਣੋ।",
  portalText: "ਹਰ ਭੂਮਿਕਾ ਲਈ ਵੱਖਰਾ ਅਨੁਭਵ, ਜਦਕਿ ਮਰੀਜ਼ ਦੀ ਮੈਡੀਕਲ ਕਹਾਣੀ ਕੇਂਦਰ ਵਿੱਚ ਰਹਿੰਦੀ ਹੈ।",
  patient: "ਮਰੀਜ਼",
  doctor: "ਡਾਕਟਰ",
  hospital: "ਹਸਪਤਾਲ",
  patientPortal: "ਮਰੀਜ਼ ਪੋਰਟਲ",
  patientPortalDesc: "ਰਿਕਾਰਡ, ਰੋਜ਼ਾਨਾ ਕੰਮ, ਦਵਾਈਆਂ ਦੀ ਅਲਮਾਰੀ ਅਤੇ ਓਟੀਪੀ ਪ੍ਰਬੰਧਨ ਕਰੋ।",
  doctorPortal: "ਡਾਕਟਰ ਪੋਰਟਲ",
  doctorPortalDesc: "ਯੂਨਿਟ ਆਈਡੀ ਨਾਲ ਮਰੀਜ਼ ਲੱਭੋ, ਰਿਕਾਰਡ ਦੇਖੋ ਅਤੇ ਵੈਦਿਆ ਓਪੀਡੀ ਕਰੋ।",
  hospitalPortal: "ਹਸਪਤਾਲ ਪੋਰਟਲ",
  hospitalPortalDesc: "ਸੰਸਥਾਗਤ ਰਿਕਾਰਡ ਤਾਲਮੇਲ, ਸਟਾਫ ਵੰਡ ਅਤੇ ਆਡਿਟ ਨਿਗਰਾਨੀ।",
  manageRecords: "ਆਪਣੇ ਰਿਕਾਰਡ ਸੰਭਾਲੋ",
  accessCare: "ਅਧਿਕਾਰਤ ਮਰੀਜ਼ ਦੀ ਜਾਣਕਾਰੀ ਵੇਖੋ",
  managePatients: "ਅਧਿਕਾਰਤ ਰਿਕਾਰਡ ਸੰਭਾਲੋ",
  welcome: "MEDILOCKER ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ",
  home: "ਹੋਮ",
  patientAccount: "ਮਰੀਜ਼ ਖਾਤਾ",
  dashboard: "ਡੈਸ਼ਬੋਰਡ",
  profilePage: "ਮੇਰਾ ਪ੍ਰੋਫਾਈਲ",
  recordsPage: "ਮੈਡੀਕਲ ਰਿਕਾਰਡ",
  uploadPage: "ਡਾਕੂਮੈਂਟ ਅੱਪਲੋਡ",
  todoPage: "ਦਵਾਈ ਟੂ-ਡੂ",
  switchPortal: "ਪੋਰਟਲ ਬਦਲੋ",
  patientDashboard: "ਮਰੀਜ਼ ਡੈਸ਼ਬੋਰਡ",
  welcomeBack: "ਜੀ ਆਇਆਂ ਨੂੰ",
  dashboardText: "ਤੁਹਾਡੀ ਸਿਹਤ ਜਾਣਕਾਰੀ ਵਿਵਸਥਿਤ ਹੈ ਅਤੇ ਲੋੜ ਵੇਲੇ ਤਿਆਰ ਹੈ।",
  viewTodo: "ਦਵਾਈ ਟੂ-ਡੂ ਵੇਖੋ ↗",
  quickAccess: "ਤੁਰੰਤ ਐਕਸੈੱਸ",
  healthAtAGlance: "ਇੱਕ ਨਜ਼ਰ ਵਿੱਚ ਤੁਹਾਡੀ ਸਿਹਤ।",
  profileHeading: "ਤੁਹਾਡਾ ਨਿੱਜੀ ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ।",
  profileHeadingText: "ਬਿਹਤਰ ਦੇਖਭਾਲ ਲਈ ਜ਼ਰੂਰੀ ਜਾਣਕਾਰੀ ਸਹੀ ਰੱਖੋ।",
  editProfile: "ਵੇਰਵੇ ਸੋਧੋ",
  verified: "ਤਸਦੀਕਸ਼ੁਦਾ ਪ੍ਰੋਫਾਈਲ",
  fullName: "ਪੂਰਾ ਨਾਮ",
  dateBirth: "ਜਨਮ ਮਿਤੀ",
  bloodGroup: "ਬਲੱਡ ਗਰੁੱਪ",
  phone: "ਫੋਨ ਨੰਬਰ",
  location: "ਟਿਕਾਣਾ",
  emergency: "ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ",
  emergencyText: "ਤੁਰੰਤ ਸਥਿਤੀ ਲਈ ਇੱਥੇ ਭਰੋਸੇਯੋਗ ਸੰਪਰਕ ਰੱਖਿਆ ਜਾ ਸਕਦਾ ਹੈ।",
  recordsHeading: "ਤੁਹਾਡੀ ਮੈਡੀਕਲ ਕਹਾਣੀ।",
  recordsHeadingText: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ, ਰਿਪੋਰਟਾਂ ਅਤੇ ਮੈਡੀਕਲ ਇਤਿਹਾਸ ਤਾਰੀਖ ਅਨੁਸਾਰ ਵਿਵਸਥਿਤ।",
  uploadNew: "ਨਵਾਂ ਅੱਪਲੋਡ ↗",
  all: "ਸਾਰੇ",
  prescriptions: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ",
  reports: "ਰਿਪੋਰਟਾਂ",
  prescription: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ",
  report: "ਲੈਬ ਰਿਪੋਰਟ",
  view: "ਵੇਖੋ",
  uploadHeading: "ਆਪਣੇ ਮੈਡੀਕਲ ਲਾਕਰ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ।",
  uploadHeadingText: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ, ਰਿਪੋਰਟਾਂ ਜਾਂ ਹੋਰ ਮੈਡੀਕਲ ਡਾਕੂਮੈਂਟ ਅੱਪਲੋਡ ਕਰੋ।",
  dropTitle: "ਡਾਕੂਮੈਂਟ ਇੱਥੇ ਰੱਖੋ",
  dropText: "ਜਾਂ ਆਪਣੇ ਡਿਵਾਈਸ ਤੋਂ ਤਸਵੀਰ ਜਾਂ PDF ਚੁਣੋ",
  chooseFile: "ਫਾਈਲ ਚੁਣੋ",
  noFile: "ਕੋਈ ਫਾਈਲ ਨਹੀਂ ਚੁਣੀ",
  documentType: "ਡਾਕੂਮੈਂਟ ਕਿਸਮ",
  other: "ਹੋਰ ਡਾਕੂਮੈਂਟ",
  documentNote: "ਨੋਟ",
  saveDocument: "ਡਾਕੂਮੈਂਟ ਸੰਭਾਲੋ ↗",
  todoHeading: "ਅੱਜ ਦੀ ਦਵਾਈ ਰੁਟੀਨ।",
  todoHeadingText: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਹਦਾਇਤਾਂ ਨੂੰ ਤੁਹਾਡੇ ਦਿਨ ਦੇ ਸੌਖੇ ਕੰਮਾਂ ਵਿੱਚ ਵਿਵਸਥਿਤ ਕੀਤਾ ਗਿਆ ਹੈ।",
  today: "ਅੱਜ",
  completed: "ਕੰਮ ਪੂਰੇ",
  routineProgress: "ਰੋਜ਼ਾਨਾ ਰੁਟੀਨ ਦੀ ਤਰੱਕੀ",
  morning: "ਸਵੇਰ",
  afternoon: "ਦੁਪਹਿਰ",
  night: "ਰਾਤ",
  withFood: "ਖਾਣੇ ਤੋਂ ਬਾਅਦ ਲਓ",
  asNeeded: "ਡਾਕਟਰ ਦੀ ਹਦਾਇਤ ਅਨੁਸਾਰ",
  routine: "ਦਿੱਤੀ ਰੁਟੀਨ ਦੀ ਪਾਲਣਾ ਕਰੋ",
  important: "ਮਹੱਤਵਪੂਰਨ",
  trust1Title: "੧੦੦% ਮਰੀਜ਼ ਦਾ ਕੰਟਰੋਲ",
  trust1Desc: "੧-ਕਲਿੱਕ ਨਾਲ ਤੁਰੰਤ ਐਕਸੈੱਸ ਰੱਦ",
  trust2Title: "ACID ਡਾਟਾਬੇਸ ਇੰਜਨ",
  trust2Desc: "ਐਂਟਰਪ੍ਰਾਈਜ਼ PostgreSQL ਸਟੋਰੇਜ",
  trust3Title: "੧੫-ਮਿੰਟ ਡਾਇਨਾਮਿਕ OTP",
  trust3Desc: "ਕਲੀਨਿਕਲ ਐਕਸੈੱਸ ਲਈ ੬-ਅੰਕੀ ਕੋਡ",
  trust4Title: "ਜ਼ੀਰੋ ਡਾਟਾ ਲੀਕ ਸਰਚ",
  trust4Desc: "ਖੋਜ ਵਿੱਚ ਸਿਰਫ ਨਾਮ ਅਤੇ ਜਨਮ ਮਿਤੀ ਦਿਖਾਈ ਦਿੰਦੀ ਹੈ"
};

T.kn = {
  ...base,
  navFeatures: "ವೈಶಿಷ್ಟ್ಯಗಳು",
  navHowItWorks: "ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
  navSecurity: "ಕ್ಲಿನಿಕಲ್ ಸುರಕ್ಷತೆ",
  navPortals: "ಪೋರ್ಟಲ್‌ಗಳು",
  setLocation: "ಸ್ಥಳ ಹೊಂದಿಸಿ",
  signIn: "ಸೈನ್ ಇನ್ ↗",
  signOut: "ಸೈನ್ ಔಟ್",
  eyebrow: "ಆರೋಗ್ಯ ನಿರ್ವಹಣೆಯ ಸುಲಭ ಮಾರ್ಗ",
  hero1: "ನಿಮ್ಮ ಆರೋಗ್ಯ ಕಥೆ,",
  hero2: "ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ.",
  heroText: "MediLocker ರೋಗಿಯ ದಾಖಲೆಗಳು, ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು, ವರದಿಗಳು ಮತ್ತು ಔಷಧಿ ದಿನಚರಿಯನ್ನು ಸುಂದರವಾಗಿ ವ್ಯವಸ್ಥಿತ ಡಿಜಿಟಲ್ ಅನುಭವಕ್ಕೆ ತರುತ್ತದೆ.",
  enter: "MediLocker ಪ್ರವೇಶಿಸಿ ↗",
  seeHow: "ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ ನೋಡಿ ↓",
  sosHero: "ತುರ್ತು SOS 102",
  designed: "ರೋಗಿಯನ್ನು ಕೇಂದ್ರವಾಗಿಟ್ಟುಕೊಂಡ ವಿನ್ಯಾಸ",
  overview: "ಆರೋಗ್ಯ ಅವಲೋಕನ",
  goodMorning: "ಶುಭೋದಯ",
  profile: "ಪ್ರೊಫೈಲ್ ಪೂರ್ಣತೆ",
  medicalRecords: "ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು",
  activeMeds: "ಸಕ್ರಿಯ ಔಷಧಿಗಳು",
  nextMedication: "ಮುಂದಿನ ಔಷಧಿ",
  afterLunch: "ಮಧ್ಯಾಹ್ನದ ಊಟದ ನಂತರ · 1:30",
  feature1: "ಒಂದು ಮೆಡಿಕಲ್ ಹೋಮ್",
  feature2: "ಸಮ್ಮತಿ ಆಧಾರಿತ ಪ್ರವೇಶ",
  feature3: "ಔಷಧಿ ಟು-ಡೂ",
  access: "ಪ್ರವೇಶ ಪೋರ್ಟಲ್‌ಗಳು",
  choosePortal: "ನಿಮ್ಮ ಕೇರ್ ಪೋರ್ಟಲ್ ಆಯ್ಕೆಮಾಡಿ.",
  portalText: "ಪ್ರತಿ ಪಾತ್ರಕ್ಕೂ ಕೇಂದ್ರೀಕೃತ ಅನುಭವ, ರೋಗಿಯ ವೈದ್ಯಕೀಯ ಕಥೆ ಕೇಂದ್ರದಲ್ಲಿರುತ್ತದೆ.",
  patient: "ರೋಗಿ",
  doctor: "ವೈದ್ಯರು",
  hospital: "ಆಸ್ಪತ್ರೆ",
  patientPortal: "ರೋಗಿ ಪೋರ್ಟಲ್",
  patientPortalDesc: "ದಾಖಲೆಗಳು, ದಿನಚರಿ, ಔಷಧಿ ಕ್ಯಾಬಿನೆಟ್ ಮತ್ತು ಒಟಿಪಿ ನಿಯೋಗಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
  doctorPortal: "ವೈದ್ಯರ ಪೋರ್ಟಲ್",
  doctorPortalDesc: "ಯುನಿಟ್ ಐಡಿ ಮೂಲಕ ರೋಗಿಗಳನ್ನು ಹುಡುಕಿ ಮತ್ತು ವೈದ್ಯ ಒಪಿಡಿ ನಿರ್ವಹಿಸಿ.",
  hospitalPortal: "ಆಸ್ಪತ್ರೆ ಪೋರ್ಟಲ್",
  hospitalPortalDesc: "ಸಂಸ್ಥೆಯ ದಾಖಲೆಗಳ ಸಮನ್ವಯ, ಸಿಬ್ಬಂದಿ ಹಂಚಿಕೆ ಮತ್ತು ಆಡಿಟ್ ಮೇಲ್ವಿಚಾರಣೆ.",
  manageRecords: "ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
  accessCare: "ಅನುಮೋದಿತ ರೋಗಿ ಮಾಹಿತಿಯನ್ನು ಪ್ರವೇಶಿಸಿ",
  managePatients: "ಅನುಮೋದಿತ ರೋಗಿ ದಾಖಲೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
  welcome: "MEDILOCKER ಗೆ ಸ್ವಾಗತ",
  home: "ಮುಖಪುಟ",
  patientAccount: "ರೋಗಿ ಖಾತೆ",
  dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  profilePage: "ನನ್ನ ಪ್ರೊಫೈಲ್",
  recordsPage: "ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು",
  uploadPage: "ಡಾಕ್ಯುಮೆಂಟ್ ಅಪ್ಲೋಡ್",
  todoPage: "ಔಷಧಿ ಟು-ಡೂ",
  switchPortal: "ಪೋರ್ಟಲ್ ಬದಲಿಸಿ",
  patientDashboard: "ರೋಗಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
  dashboardText: "ನಿಮ್ಮ ಆರೋಗ್ಯ ಮಾಹಿತಿ ವ್ಯವಸ್ಥಿತವಾಗಿದೆ ಮತ್ತು ಅಗತ್ಯವಿದ್ದಾಗ ಸಿದ್ಧವಾಗಿದೆ.",
  viewTodo: "ಔಷಧಿ ಟು-ಡೂ ನೋಡಿ ↗",
  quickAccess: "ತ್ವರಿತ ಪ್ರವೇಶ",
  healthAtAGlance: "ಒಂದು ನೋಟದಲ್ಲಿ ನಿಮ್ಮ ಆರೋಗ್ಯ.",
  profileHeading: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್.",
  profileHeadingText: "ಉತ್ತಮ ಆರೈಕೆಗಾಗಿ ಅಗತ್ಯ ಮಾಹಿತಿಯನ್ನು ಸರಿಯಾಗಿ ಇಡಿ.",
  editProfile: "ವಿವರಗಳನ್ನು ಸಂಪಾದಿಸಿ",
  verified: "ಪರಿಶೀಲಿಸಿದ ಪ್ರೊಫೈಲ್",
  fullName: "ಪೂರ್ಣ ಹೆಸರು",
  dateBirth: "ಜನ್ಮ ದಿನಾಂಕ",
  bloodGroup: "ರಕ್ತದ ಗುಂಪು",
  phone: "ಫೋನ್ ಸಂಖ್ಯೆ",
  location: "ಸ್ಥಳ",
  emergency: "ತುರ್ತು ಸಂಪರ್ಕ",
  emergencyText: "ತುರ್ತು ಪರಿಸ್ಥಿತಿಗಾಗಿ ಇಲ್ಲಿ ವಿಶ್ವಾಸಾರ್ಹ ಸಂಪರ್ಕವನ್ನು ಇಡಬಹುದು.",
  recordsHeading: "ನಿಮ್ಮ ವೈದ್ಯಕೀಯ ಕಥೆ.",
  recordsHeadingText: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್, ವರದಿಗಳು ಮತ್ತು ವೈದ್ಯಕೀಯ ಇತಿಹಾಸವನ್ನು ದಿನಾಂಕದಂತೆ ವ್ಯವಸ್ಥಿತಗೊಳಿಸಲಾಗಿದೆ.",
  uploadNew: "ಹೊಸ ಅಪ್ಲೋಡ್ ↗",
  all: "ಎಲ್ಲಾ",
  prescriptions: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು",
  reports: "ವರದಿಗಳು",
  prescription: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್",
  report: "ಲ್ಯಾಬ್ ವರದಿ",
  view: "ನೋಡಿ",
  uploadHeading: "ನಿಮ್ಮ ಮೆಡಿಕಲ್ ಲಾಕರ್‌ಗೆ ಸೇರಿಸಿ.",
  uploadHeadingText: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್, ವರದಿ ಅಥವಾ ಇತರ ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ.",
  dropTitle: "ಡಾಕ್ಯುಮೆಂಟ್ ಇಲ್ಲಿ ಹಾಕಿ",
  dropText: "ಅಥವಾ ಸಾಧನದಿಂದ ಚಿತ್ರ ಅಥವಾ PDF ಆಯ್ಕೆಮಾಡಿ",
  chooseFile: "ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ",
  noFile: "ಯಾವುದೇ ಫೈಲ್ ಆಯ್ಕೆ ಮಾಡಿಲ್ಲ",
  documentType: "ಡಾಕ್ಯುಮೆಂಟ್ ಪ್ರಕಾರ",
  other: "ಇತರೆ ಡಾಕ್ಯುಮೆಂಟ್",
  documentNote: "ಟಿಪ್ಪಣಿ",
  saveDocument: "ಡಾಕ್ಯುಮೆಂಟ್ ಉಳಿಸಿ ↗",
  todoHeading: "ಇಂದಿನ ಔಷಧಿ ದಿನಚರಿ.",
  todoHeadingText: "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಸೂಚನೆಗಳನ್ನು ನಿಮ್ಮ ದಿನದ ಸರಳ ಕಾರ್ಯಗಳಾಗಿ ವ್ಯವಸ್ಥಿತಗೊಳಿಸಲಾಗಿದೆ.",
  today: "ಇಂದು",
  completed: "ಕಾರ್ಯಗಳು ಪೂರ್ಣ",
  routineProgress: "ದೈನಂದಿನ ದಿನಚರಿ ಪ್ರಗತಿ",
  morning: "ಬೆಳಗ್ಗೆ",
  afternoon: "ಮಧ್ಯಾಹ್ನ",
  night: "ರಾತ್ರಿ",
  withFood: "ಆಹಾರದ ನಂತರ ತೆಗೆದುಕೊಳ್ಳಿ",
  asNeeded: "ವೈದ್ಯರ ಸೂಚನೆಯಂತೆ",
  routine: "ನಿಗದಿತ ದಿನಚರಿಯನ್ನು ಅನುಸರಿಸಿ",
  important: "ಮುಖ್ಯ",
  trust1Title: "100% ರೋಗಿಯ ನಿಯಂತ್ರಣ",
  trust1Desc: "ತಕ್ಷಣದ 1-ಕ್ಲಿಕ್ ಪ್ರವೇಶ ರದ್ದತಿ",
  trust2Title: "ACID ಡೇಟಾಬೇಸ್ ಎಂಜಿನ್",
  trust2Desc: "ಎಂಟರ್‌ಪ್ರೈಸ್ PostgreSQL ಸಂಗ್ರಹಣೆ",
  trust3Title: "15-ನಿಮಿಷದ ಡೈನಾಮಿಕ್ OTP",
  trust3Desc: "ವೈದ್ಯಕೀಯ ಪ್ರವೇಶಕ್ಕಾಗಿ 6-ಅಂಕಿಯ ಕೋಡ್",
  trust4Title: "ಶೂನ್ಯ ಡೇಟಾ ಸೋರಿಕೆ ಹುಡುಕಾಟ",
  trust4Desc: "ಹುಡುಕಾಟದಲ್ಲಿ ಹೆಸರು ಮತ್ತು ಜನ್ಮದಿನಾಂಕ ಮಾತ್ರ ಗೋಚರ"
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      return localStorage.getItem('medilockerLanguage') || 'en';
    } catch (e) {
      return 'en';
    }
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('medilockerLanguage', lang);
    } catch (e) {}
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ur' ? 'rtl' : 'ltr';
  };

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ur' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key, fallback = '') => {
    const dict = T[language] || T.en;
    if (dict && dict[key]) return dict[key];
    if (T.en && T.en[key]) return T.en[key];
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir: language === 'ur' ? 'rtl' : 'ltr' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'en',
      setLanguage: () => {},
      t: (k, fb = '') => fb || k,
      dir: 'ltr'
    };
  }
  return context;
}
