(function(){
  const ACCOUNTS_KEY='medilockerAccounts';
  const SESSION_KEY='medilockerSession';
  const getAccounts=()=>{try{return JSON.parse(localStorage.getItem(ACCOUNTS_KEY)||'[]')}catch(e){return[]}};
  const saveAccounts=a=>localStorage.setItem(ACCOUNTS_KEY,JSON.stringify(a));
  const getSession=()=>{try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch(e){return null}};
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const initials=n=>(n||'User').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  const currentT=()=>window.T?.[localStorage.getItem('medilockerLanguage')||'en']||window.T?.en||{};

  function bindLanguage(){const s=document.getElementById('languageSelect');if(!s)return;s.value=localStorage.getItem('medilockerLanguage')||'en';s.addEventListener('change',e=>window.applyLanguage?.(e.target.value));}
  function bindLocation(){document.querySelectorAll('#locationBtn').forEach(b=>b.addEventListener('click',()=>{if(!navigator.geolocation){alert('Geolocation is not supported by this browser.');return}const old=b.innerHTML;b.disabled=true;b.innerHTML='⌖ Detecting…';navigator.geolocation.getCurrentPosition(pos=>{const lat=pos.coords.latitude.toFixed(4),lon=pos.coords.longitude.toFixed(4);localStorage.setItem('medilockerLocation',`${lat}, ${lon}`);document.querySelectorAll('#locationBtn span').forEach(x=>x.textContent=`${lat}, ${lon}`);const d=document.getElementById('locationDisplay');if(d)d.textContent=`Location detected · ${lat}, ${lon}`;b.disabled=false;b.innerHTML=old;alert('Location permission granted. Your current location has been set.')},err=>{b.disabled=false;b.innerHTML=old;alert(err.code===1?'Location permission was denied. Please allow location access in your browser.':'Unable to detect your location. Please try again.')},{enableHighAccuracy:true,timeout:10000,maximumAge:0})}));const v=localStorage.getItem('medilockerLocation');if(v)document.querySelectorAll('#locationBtn span').forEach(x=>x.textContent=v)}

  function updateLoginRole(role){const t=currentT(),m={patient:['patientLogin','patientLoginText','♡'],doctor:['doctorLogin','doctorLoginText','✚'],hospital:['hospitalLogin','hospitalLoginText','▦']};const title=document.getElementById('loginTitle'),sub=document.getElementById('loginSubtitle'),sym=document.getElementById('roleSymbol');if(!title||!sub)return;const x=m[role]||m.patient;title.textContent=t[x[0]]||({patient:'Patient login',doctor:'Doctor login',hospital:'Hospital login'}[role]);sub.textContent=t[x[1]]||({patient:'Sign in to manage your medical records.',doctor:'Sign in to access the doctor workspace.',hospital:'Sign in to access the hospital workspace.'}[role]);if(sym)sym.textContent=x[2];document.querySelectorAll('.role-tab').forEach(b=>b.classList.toggle('active',b.dataset.role===role));}
  function bindLogin(){let role=new URLSearchParams(location.search).get('role')||'patient';if(!['patient','doctor','hospital'].includes(role))role='patient';window.currentRole=role;document.querySelectorAll('.role-tab').forEach(b=>b.addEventListener('click',()=>{window.currentRole=b.dataset.role;updateLoginRole(window.currentRole);history.replaceState({},'',`login.html?role=${window.currentRole}`)}));updateLoginRole(role);const f=document.getElementById('loginForm');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();const email=f.querySelector('input[type=email]').value.trim().toLowerCase();const unit=document.getElementById('unitId').value.trim().toUpperCase();const saved=getAccounts().find(a=>String(a.email||'').toLowerCase()===email&&String(a.unit||'').toUpperCase()===unit);if(!saved){alert('No matching account found. Use the exact registered email and Unit ID generated during Sign Up.');return}if(saved.role!==window.currentRole){alert(`This Unit ID belongs to a ${saved.role} account. Please select the correct portal.`);return}localStorage.setItem(SESSION_KEY,JSON.stringify({unit:saved.unit,email:saved.email,role:saved.role}));location.href=saved.role==='doctor'?'doctor.html':saved.role==='hospital'?'hospital.html':'dashboard.html'});}

  function setSignupRole(role){const sections={patient:document.getElementById('patientFields'),doctor:document.getElementById('doctorFields'),hospital:document.getElementById('hospitalFields')};Object.entries(sections).forEach(([k,el])=>el?.classList.toggle('hidden',k!==role));document.querySelectorAll('input[name=role]').forEach(r=>r.closest('.signup-role')?.classList.toggle('selected',r.value===role));document.querySelectorAll('[data-required]').forEach(el=>{el.required=el.dataset.required===role});document.body.dataset.signupRole=role;}
  function bindSignup(){const f=document.getElementById('signupForm');if(!f)return;let role='patient';document.querySelectorAll('input[name=role]').forEach(r=>r.addEventListener('change',()=>{role=r.value;setSignupRole(role)}));setSignupRole(role);
    f.addEventListener('submit',e=>{e.preventDefault();setSignupRole(role);if(!f.reportValidity())return;const fd=new FormData(f);let data={role,createdAt:new Date().toISOString()};if(role==='patient'){Object.assign(data,{name:fd.get('patientName'),email:fd.get('patientEmail'),phone:fd.get('patientPhone'),dob:fd.get('dob'),gender:fd.get('gender'),blood:fd.get('blood'),govid:fd.get('govid'),insurance:fd.get('insurance'),allergy:fd.get('allergy'),medications:fd.get('medications'),history:fd.get('history'),emergency:fd.get('emergency'),address:fd.get('address'),city:fd.get('city'),state:fd.get('state'),pincode:fd.get('pincode')})}else if(role==='doctor'){Object.assign(data,{name:fd.get('doctorName'),email:fd.get('doctorEmail'),phone:fd.get('doctorPhone'),doctorId:fd.get('doctorId'),registrationNumber:fd.get('registrationNumber'),specialization:fd.get('specialization'),registrationDate:fd.get('registrationDate'),experience:fd.get('experience'),clinicName:fd.get('clinicName'),clinicVerification:fd.get('clinicVerification'),address:fd.get('clinicAddress'),city:fd.get('doctorCity'),state:fd.get('doctorState'),verification:fd.get('doctorVerification')})}else{Object.assign(data,{name:fd.get('hospitalName'),email:fd.get('hospitalEmail'),phone:fd.get('hospitalPhone'),hospitalId:fd.get('hospitalId'),license:fd.get('hospitalLicense'),registrationDate:fd.get('hospitalRegDate'),address:fd.get('hospitalAddress'),city:fd.get('hospitalCity'),state:fd.get('hospitalState'),hospitalType:fd.get('hospitalType'),beds:fd.get('beds'),representative:fd.get('representative'),verification:fd.get('hospitalVerification'),verificationRef:fd.get('hospitalVerificationRef')})}
      if(getAccounts().some(a=>String(a.email||'').toLowerCase()===String(data.email).toLowerCase())){alert('An account with this email already exists. Use another email or sign in with the existing Unit ID.');return}
      let unit;do{unit='ML-'+Math.random().toString(36).slice(2,6).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}while(getAccounts().some(a=>a.unit===unit));data.unit=unit;const accounts=getAccounts();accounts.push(data);saveAccounts(accounts);localStorage.setItem('medilockerLastCreatedUnit',unit);localStorage.setItem('medilockerLastCreatedRole',role);document.getElementById('generatedUnit').textContent=unit;document.getElementById('unitMessage').innerHTML=`Your <strong>${esc(role)}</strong> account is ready. Save <strong>${esc(unit)}</strong> and use it with <strong>${esc(data.email)}</strong> to sign in.`;document.getElementById('unitModal')?.classList.remove('hidden');});
    document.getElementById('closeUnit')?.addEventListener('click',()=>document.getElementById('unitModal')?.classList.add('hidden'));document.getElementById('goLogin')?.addEventListener('click',()=>location.href=`login.html?role=${encodeURIComponent(localStorage.getItem('medilockerLastCreatedRole')||'patient')}`);
  }

  function requireSession(role){const s=getSession();if(!s||s.role!==role){location.href=`login.html?role=${role}`;return null}return getAccounts().find(a=>a.unit===s.unit&&a.role===role)||null;}
  function bindPatientUI(){const a=requireSession('patient');if(!a)return;document.querySelectorAll('[data-user-name]').forEach(e=>e.textContent=a.name||'Patient');document.querySelectorAll('[data-user-email]').forEach(e=>e.textContent=a.email||'');document.querySelectorAll('[data-user-unit]').forEach(e=>e.textContent=a.unit);document.querySelectorAll('[data-user-initials]').forEach(e=>e.textContent=initials(a.name));const fields={fullName:a.name||'',dateBirth:a.dob||'Not provided',bloodGroup:a.blood||'Not specified',phone:a.phone||'Not provided',email:a.email||'',location:[a.city,a.state].filter(Boolean).join(', ')||'Not provided',govid:a.govid||'Not provided',insurance:a.insurance||'Not provided',allergy:a.allergy||'None recorded',medications:a.medications||'None recorded',history:a.history||'Not provided',emergency:a.emergency||'Not provided',address:a.address||'Not provided'};Object.entries(fields).forEach(([k,v])=>document.querySelectorAll(`[data-field="${k}"]`).forEach(e=>e.value=v));}
  function bindPatientRecords(){const a=requireSession('patient');if(!a)return;document.querySelectorAll('.record-empty-user').forEach(e=>e.textContent=a.name||'your');document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const type=b.dataset.filter;document.querySelectorAll('.record-card').forEach(c=>c.style.display=type==='all'||c.dataset.type===type?'flex':'none')}));}
  function patientDataCard(a){return `<div class="patient-result-head"><div class="large-avatar">${esc(initials(a.name))}</div><div><span class="eyebrow">PATIENT FOUND</span><h2>${esc(a.name)}</h2><p>${esc(a.unit)} · ${esc([a.city,a.state].filter(Boolean).join(', ')||'Location not provided')}</p></div><span class="status-pill">Authorization required</span></div><div class="patient-result-grid"><div><small>DATE OF BIRTH</small><strong>${esc(a.dob||'Not provided')}</strong></div><div><small>ALLERGIES</small><strong>${esc(a.allergy||'None recorded')}</strong></div><div><small>MEDICATIONS</small><strong>${esc(a.medications||'None recorded')}</strong></div><div><small>MEDICAL HISTORY</small><strong>${esc(a.history||'Not provided')}</strong></div><div><small>EMERGENCY CONTACT</small><strong>${esc(a.emergency||'Not provided')}</strong></div><div><small>INSURANCE</small><strong>${esc(a.insurance||'Not provided')}</strong></div></div><div class="authorization-note">Prototype access: patient lookup is demonstrated locally. Production access must require verified provider identity and explicit patient authorization.</div>`;}
  function bindProviderPortal(role){const a=requireSession(role);if(!a)return;document.querySelectorAll('[data-provider-name]').forEach(e=>e.textContent=a.name||role);document.querySelectorAll('[data-provider-unit]').forEach(e=>e.textContent=a.unit);document.querySelectorAll('[data-provider-initials]').forEach(e=>e.textContent=initials(a.name));const form=document.getElementById('patientSearchForm'),input=document.getElementById('patientUnitSearch'),result=document.getElementById('patientSearchResult'),empty=document.getElementById('patientSearchEmpty');if(form)form.addEventListener('submit',e=>{e.preventDefault();const unit=input.value.trim().toUpperCase(),patient=getAccounts().find(x=>x.role==='patient'&&String(x.unit).toUpperCase()===unit);if(patient){result.innerHTML=patientDataCard(patient);result.classList.remove('hidden');empty?.classList.add('hidden')}else{result.classList.add('hidden');empty?.classList.remove('hidden');if(empty)empty.innerHTML=`<div class="empty-icon">⌕</div><h3>No patient found</h3><p>No patient account matches <strong>${esc(unit||'that Unit ID')}</strong>. Ask the patient to provide their exact MediLocker Unit ID.</p>`}})}
  function bindLogout(){document.querySelectorAll('[data-logout]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();localStorage.removeItem(SESSION_KEY);location.href='index.html'}));}
  function bindUpload(){const i=document.getElementById('fileInput'),n=document.getElementById('fileName'),d=document.getElementById('dropZone');if(i)i.addEventListener('change',()=>{if(n)n.textContent=i.files[0]?i.files[0].name:currentT().noFile});if(d){['dragenter','dragover'].forEach(e=>d.addEventListener(e,x=>{x.preventDefault();d.classList.add('dragging')}));['dragleave','drop'].forEach(e=>d.addEventListener(e,x=>{x.preventDefault();d.classList.remove('dragging')}));d.addEventListener('drop',x=>{const files=x.dataTransfer.files;if(files.length&&i){try{i.files=files}catch(_){}if(n)n.textContent=files[0].name}})}document.getElementById('saveUpload')?.addEventListener('click',()=>alert('Document selected successfully. Storage and OCR/processing will be connected during backend integration.'))}
  function bindTodo(){const boxes=[...document.querySelectorAll('.med-task input')],count=document.getElementById('doneCount'),bar=document.getElementById('todoProgress');function update(){const done=boxes.filter(x=>x.checked).length;if(count)count.textContent=`${done} / ${boxes.length}`;if(bar)bar.style.width=`${boxes.length?done/boxes.length*100:0}%`}boxes.forEach(x=>x.addEventListener('change',update));update();}
  document.addEventListener('DOMContentLoaded',()=>{bindLanguage();bindLocation();window.applyLanguage?.(localStorage.getItem('medilockerLanguage')||'en');bindLogout();if(document.body.classList.contains('login-page')&&document.getElementById('loginForm'))bindLogin();if(document.getElementById('signupForm'))bindSignup();if(document.querySelector('.patient-dashboard'))bindPatientUI();if(document.querySelector('.patient-records'))bindPatientRecords();if(document.querySelector('.provider-portal'))bindProviderPortal(document.body.dataset.providerRole);if(document.getElementById('fileInput'))bindUpload();if(document.querySelector('.med-task'))bindTodo();});
})();
